### ISSUE TITLE
Failed two tests: testGetRecipientsForQuestionOwnTeamMembersIncludingSelf, testGetRecipientsForQuestiondDefault

### ISSUE THREAD

**Issue by valsen** [valsen/teammates#49]
The following two tests are failing:
testGetRecipientsForQuestionOwnTeamMembersIncludingSelf
testGetRecipientsForQuestiondDefault

![Screenshot 2020-02-18 at 00 37 24](https://user-images.githubusercontent.com/529685/74692770-0321d480-51e9-11ea-8451-06ea912920a4.png)

**Comment by christinasunnegardh** [comment]
6dbf38c6a6bd9faa05dc4927e57ab7851ac39e0e closes this.
